# Generated by Django 5.2.14 on 2026-05-15 08:30

from django.db import migrations


def initial_accounts(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")

    accounts = [
        Account(
            code="1000",
            name="cash/bank",
            type="asset",
            normal_side="debit",
        ),
        Account(
            code="1001",
            name="Accounts Receivable",
            type="asset",
            normal_side="debit",
        ),
        Account(
            code="1002",
            name="Student Deposit",
            type="liability",
            normal_side="credit",
        ),
        Account(
            code="1003",
            name="Fee Income",
            type="income",
            normal_side="credit",
        ),
        Account(
            code="1004",
            name="Discount",
            type="contra_revenue",
            normal_side="debit",
        ),
    ]

    Account.objects.bulk_create(accounts)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_accounts)
    ]
